_services/1j-sgus-manage-retail-and-enterprise-in-the-digital-age.md, _services/1k-sgus-digital-and-leadership-skills-to-excel-in-the-future-of-retail-and-business.md
Amended/created who should attend
=> SGUS Programmes

_digital-programmes/3f-getting-started-on-lazada.md
=> Update of Lazada Dates

_digital-programmes/3c-amazon-global-selling-programme.md, _digital-programmes/3e-ebay-global-selling.md, _digital-programmes/3g-drive-sales-performance-on-lazada.md, _digital-programmes/3h-getting-started-on-qoo10.md, _digital-programmes/3i-drive-sales-performance-on-qoo10.md, _digital-programmes/3j-getting-started-on-shopee.md, _digital-programmes/3k-driving-sales-performance-on-shopee.md, _digital-programmes/3m-setup-an-online-business, _digital-programmes/5r-level-up-customer-engagement-with-live-streaming.md, _digital-programmes/7-skillsfuture-digital-workplace, _digital-programmes/8b-basics-in-content-generation.md, _digital-programmes/8c-engage-customers-through-social-media.md, _digital-programmes/8d-fundamentals-to-starting-an-online-business.md, _digital-programmes/8e-introduction-to-data-analytics.md, _digital-programmes/8f-introduction-to-digital-marketing.md, _digital-programmes/8g-personal-online-branding.md, _digital-programmes/8h-tap-into-the-power-of-instagram-for-selling.md, _digital-programmes/8i-thrive-in-digital-disruption.md, _retail-programmes/1b-certificate-in-retail-operations.md, _retail-programmes/1c-advanced-certificate-in-retail-operations.md, _retail-programmes/1d-diploma-in-retail-operations.md, _retail-programmes/1e-specialist-diploma-in-retail-operations.md, _retail-programmes/2c-creating-an-unforgettable-customer-experience.md, _retail-programmes/2d-mastering-the-art-of-selling-in-new-retail.md, _retail-programmes/2e-maximising-digital-ad-dollars-with-sem.md, _retail-programmes/2f-search-engine-optimisation-game-plan.md, _retail-programmes/2h-unleash-the-power-of-social-media-merchandising.md
Update all the class intakes for courses under CRC.
=> Update of Class intakes for CRC

_retail-programmes/1c-advanced-certificate-in-retail-operations.md, _retail-programmes/1d-diploma-in-retail-operations.md
ACRO and DRO - removed extra and added missing brackets
=> WSQ - Amend brackets

Archive-for-Hidden-Pages, _digital-programmes/3a-e-commerce-programmes.md, _digital-programmes/3m-setup-an-online-business.md
Unhide page and added course in overview page
=> E-Commerce Prog - Set Up an Online Business

_services/1i-sgus-programme.md
Changed Register for Interest to Register Now
=> SGUS Overview - Register Button

_digital-programmes/5j-digital-commerce-visual.md, _digital-programmes/5k-digital-strategy-and-the-101-of-seo.md, _digital-programmes/5t-omni-commerce-retail.md
=> Update of reg links 

_services/1h-work-study-cert-dmb.md
=> Update of reg link for WLB 

_digital-programmes/5ri-master-facebook-marketing-for-business.md, _digital-programmes/5rii-master-linkedin-for-sales-and-marketing.md
https://nyp-sirs-staging.netlify.app/digital-programmes/masterclasses-and-workshops/master-facebook-marketing-for-business
https://nyp-sirs-staging.netlify.app/digital-programmes/masterclasses-and-workshops/master-linkedin-for-sales-and-marketing
=> Hyperlinks in Masterclasses

_digital-programmes/3m-setup-an-online-business.md
https://nyp-sirs-staging.netlify.app/digital-programmes/e-commerce-programmes/setup-an-online-business
https://www.sirs.edu.sg/digital-programmes/e-commerce-programmes/setup-an-online-business
Half of the fixed list has already been pushed with other changes earlier.
=> Fixing list code 

_digital-programmes/1f-alibaba-content-marketing-programme.md, _digital-programmes/5ri-master-facebook-marketing-for-business.md
For ATU Content Marketing and Masterclass Facebook
=> Update intake dates for Jiawen

_success-and-blog/success-stories/fruit-paradise.md
Amended name of owner as highlighted by Lynda.
=> Update file: success-stories/fruit-paradise.md

_services/career-services/sgus-digital-leadership-skills-to-excel-in-the-future-of-retail-business.md, _services/career-services/sgus-manage-retail-enterprise-in-the-digital-age.md
=> Update dates for SGUS

_digital-programmes/masterclasses-workshops/grow-your-brand-presence-with-wechat-marketing.md
Update date for wechat marketing
=> Update date for wechat marketing

_digital-programmes/masterclasses-workshops/grow-your-brand-presence-with-wechat-marketing.md
=> Change Wechat reg link

_digital-programmes/alibaba-business-school/overview.md, _services/career-services/sgus-digital-leadership-skills-to-excel-in-the-future-of-retail-business.md, _services/career-services/sgus-manage-retail-enterprise-in-the-digital-age.md
=> Updates dates for SGUS

_digital-programmes/SkillsFuture-series/basics-in-content-generation.md, _digital-programmes/SkillsFuture-series/engage-customers-through-social-media.md, _digital-programmes/SkillsFuture-series/fundamentals-to-starting-an-online-business.md, _digital-programmes/SkillsFuture-series/introduction-to-data-analytics.md, _digital-programmes/SkillsFuture-series/introduction-to-digital-marketing.md, _digital-programmes/SkillsFuture-series/personal-online-branding.md, _digital-programmes/SkillsFuture-series/tap-into-the-power-of-instagram-for-selling.md, _digital-programmes/SkillsFuture-series/thrive-in-digital-disruption.md, _digital-programmes/e-commerce-programmes/amazon-global-selling-onboarding.md, _digital-programmes/e-commerce-programmes/drive-sales-performance-on-lazada-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-qoo10-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-shopee-marketing.md, _digital-programmes/e-commerce-programmes/ebay-global-selling-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-lazada-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-qoo10-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-shopee-onboarding.md, _digital-programmes/e-commerce-programmes/set-up-an-online-business.md, _digital-programmes/masterclasses-workshops/digital-commerce-visual.md, _digital-programmes/masterclasses-workshops/digital-strategy-the-101-of-search-engine-optimisation-seo.md, _digital-programmes/masterclasses-workshops/level-up-customer-engagement-through-live-streaming.md, _digital-programmes/masterclasses-workshops/omni-commerce-retail.md, _digital-programmes/skillsfuture-for-digital-workplace-sfdw.md, _wsq-programmes/WSQ-certified-modular-programmes/creating-an-unforgettable-customer-experience.md, _wsq-programmes/WSQ-certified-modular-programmes/mastering-the-art-of-selling-in-new-retail.md, _wsq-programmes/WSQ-certified-modular-programmes/the-art-and-science-of-visual-merchandising.md, _wsq-programmes/WSQ-certified-modular-programmes/unleash-the-power-of-social-media-marketing.md, _wsq-programmes/WSQ-full-qualification-programmes/diploma-in-retail-e-commerce-omni-channel.md, _wsq-programmes/WSQ-full-qualification-programmes/diploma-in-retail-operations.md, _wsq-programmes/WSQ-full-qualification-programmes/specialist-diploma-in-retail-operations.md
Update intake dates and Mid-Career Enhanced Subsidy
=> Update intake dates and Mid-Career Enhanced Subsidy

_digital-programmes/e-commerce-programmes/getting-started-on-lazada-onboarding.md
Correct an error in alignment for lazada onboarding
=> Correct an error in alignment for lazada onboarding

_digital-programmes/masterclasses-workshops/grow-your-brand-presence-with-wechat-marketing.md
=> New Class date for Wechat

_services/career-services/sgus-manage-retail-enterprise-in-the-digital-age.md, _services/career-services/skillsfuture-work-study-certificate-bootcamp-in-digital-marketing-branding.md
=> Update date for SGUSRE

_about-us/who-we-are.md, _data/footer.yml, _wsq-programmes/WSQ-certified-modular-programmes/mastering-the-art-of-selling-in-new-retail.md, _wsq-programmes/WSQ-certified-modular-programmes/the-art-and-science-of-visual-merchandising.md, _wsq-programmes/overview.md
Updated:
1. Who We Are (Added Liner on UEN and SSG)
2. WSQ Modular Courses - VM and Service Leadership (Added Mode of Training and Funding Eligibility Period)
=> Updates to WSQ Modular Courses and Who We Are (SSG)

_wsq-programmes/WSQ-full-qualification-programmes/advanced-certificate-in-retail-operations.md, _wsq-programmes/WSQ-full-qualification-programmes/diploma-in-retail-e-commerce-omni-channel.md, _wsq-programmes/WSQ-full-qualification-programmes/diploma-in-retail-operations.md, _wsq-programmes/WSQ-full-qualification-programmes/specialist-diploma-in-retail-operations.md
=> Update of WSQ Full Qua Dates

_digital-programmes/e-commerce-programmes/drive-sales-performance-on-lazada-marketing.md, _digital-programmes/e-commerce-programmes/getting-started-on-lazada-onboarding.md
=> update Lazada dates 

_services/career-services/skillsfuture-work-study-certificate-bootcamp-in-digital-marketing-branding.md, _wsq-programmes/WSQ-certified-modular-programmes/maximise-digital-advertising-dollars-with-search-engine-marketing-sem.md, _wsq-programmes/WSQ-certified-modular-programmes/search-engine-optimization-seo-game-plan.md
Update of dates for WSQ modular and WLB
=> Update of dates for WSQ modular and WLB

_wsq-programmes/WSQ-certified-modular-programmes/maximise-digital-advertising-dollars-with-search-engine-marketing-sem.md, _wsq-programmes/WSQ-certified-modular-programmes/search-engine-optimization-seo-game-plan.md, _wsq-programmes/WSQ-certified-modular-programmes/unleash-the-power-of-social-media-marketing.md
=> remove (4days)

_digital-programmes/masterclasses-&-workshops/start-grow-and-scale-online.md, _wsq-programmes/WSQ-certified-modular-programmes/search-engine-optimization-seo-game-plan.md
Workshop (SourceSage) and WSQ Modular (SEO Game Plan)
=> Updates - Typos

index.md
=> Homepage - Highlights

_digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md
1) Amend next intake to TBC and added Register Interest Link
2) Amend Register Now button to Register for Interest
=> Alibaba ESP

_services/career-services/sgus-omni-commerce-and-digital-marketing.md
=> Update SGUS Omni Date

_services/career-services/sgus-digital-and-leadership-skills-to-excel-in-the-future-of-retail-and-business.md, _services/career-services/sgus-manage-retail-enterprise-in-the-digital-age.md
=> Update SGUS Dates 

_digital-programmes/masterclasses-&-workshops/master-linkedin-for-sales-marketing.md
=> Update file: master-linkedin-for-sales-marketing.md

_digital-programmes/masterclasses-&-workshops/level-up-customer-engagement-through-live-streaming.md
Update Date for Livestreaming Workshop
=> Update Date for Livestreaming Workshop

_digital-programmes/SkillsFuture-series/basics-in-content-generation.md, _digital-programmes/SkillsFuture-series/engage-customers-through-social-media.md, _digital-programmes/SkillsFuture-series/fundamentals-to-starting-an-online-business.md, _digital-programmes/SkillsFuture-series/introduction-to-data-analytics.md, _digital-programmes/SkillsFuture-series/introduction-to-digital-marketing.md, _digital-programmes/SkillsFuture-series/personal-online-branding.md, _digital-programmes/SkillsFuture-series/tap-into-the-power-of-instagram-for-selling.md, _digital-programmes/SkillsFuture-series/thrive-in-digital-disruption.md, _digital-programmes/e-commerce-programmes/amazon-global-selling-onboarding.md, _digital-programmes/e-commerce-programmes/drive-sales-performance-on-lazada-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-qoo10-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-shopee-marketing.md, _digital-programmes/e-commerce-programmes/ebay-global-selling-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-lazada-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-qoo10-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-shopee-onboarding.md, _digital-programmes/e-commerce-programmes/set-up-an-online-business.md, _digital-programmes/masterclasses-&-workshops/digital-commerce-visual.md, _digital-programmes/masterclasses-&-workshops/digital-strategy-the-101-of-search-engine-optimisation-seo.md, _digital-programmes/masterclasses-&-workshops/level-up-customer-engagement-through-live-streaming.md, _digital-programmes/masterclasses-&-workshops/omni-commerce-retail.md, _digital-programmes/skillsfuture-for-digital-workplace-sfdw.md, _wsq-programmes/WSQ-certified-modular-programmes/mastering-the-art-of-selling-in-new-retail.md, _wsq-programmes/WSQ-certified-modular-programmes/maximise-digital-advertising-dollars-with-search-engine-marketing-sem.md, _wsq-programmes/WSQ-certified-modular-programmes/search-engine-optimization-seo-game-plan.md, _wsq-programmes/WSQ-certified-modular-programmes/the-art-and-science-of-visual-merchandising.md, _wsq-programmes/WSQ-certified-modular-programmes/unleash-the-power-of-social-media-marketing.md
Update intake dates for all CRC courses
=> Update intake dates for all CRC courses 

_digital-programmes/masterclasses-&-workshops/grow-your-brand-presence-with-wechat-marketing.md
Update dates for Wechat Marketing to TBC
=> Update dates for Wechat Marketing to TBC 

_digital-programmes/e-commerce-programmes/best-practices-of-e-commerce-transactions-esg-tr-76.md
=> Update file: best-practices-of-e-commerce-transactions-esg-tr-76.md

_digital-programmes/skillsfuture-for-digital-workplace-sfdw.md
=> Add new date for SFDW

_services/career-services/sgus-digital-and-leadership-skills-to-excel-in-the-future-of-retail-and-business.md, _services/career-services/sgus-manage-retail-enterprise-in-the-digital-age.md, _services/career-services/sgus-omni-commerce-and-digital-marketing.md
=> Update of SGUS Dates 

_digital-programmes/SkillsFuture-series/basics-in-content-generation.md, _digital-programmes/SkillsFuture-series/engage-customers-through-social-media.md, _digital-programmes/SkillsFuture-series/fundamentals-to-starting-an-online-business.md, _digital-programmes/SkillsFuture-series/introduction-to-data-analytics.md, _digital-programmes/SkillsFuture-series/introduction-to-digital-marketing.md, _digital-programmes/SkillsFuture-series/personal-online-branding.md, _digital-programmes/SkillsFuture-series/tap-into-the-power-of-instagram-for-selling.md, _digital-programmes/SkillsFuture-series/thrive-in-digital-disruption.md, _digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md, _digital-programmes/e-commerce-programmes/amazon-global-selling-onboarding.md, _digital-programmes/e-commerce-programmes/drive-sales-performance-on-lazada-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-qoo10-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-shopee-marketing.md, _digital-programmes/e-commerce-programmes/getting-started-on-lazada-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-qoo10-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-shopee-onboarding.md, _digital-programmes/e-commerce-programmes/set-up-an-online-business.md, _digital-programmes/masterclasses-&-workshops/digital-commerce-visual.md, _digital-programmes/masterclasses-&-workshops/digital-strategy-the-101-of-search-engine-optimisation-seo.md, _digital-programmes/masterclasses-&-workshops/level-up-customer-engagement-through-live-streaming.md, _digital-programmes/masterclasses-&-workshops/omni-commerce-retail.md, _digital-programmes/masterclasses-&-workshops/start-grow-and-scale-online.md, _wsq-programmes/WSQ-certified-modular-programmes/creating-an-unforgettable-customer-experience.md, _wsq-programmes/WSQ-certified-modular-programmes/mastering-the-art-of-selling-in-new-retail.md, _wsq-programmes/WSQ-certified-modular-programmes/the-art-and-science-of-visual-merchandising.md
Update intake takes for CRC courses
=> Update intake takes for CRC courses 

_digital-programmes/masterclasses-&-workshops/start-grow-and-scale-online.md
Update file: start-grow-and-scale-online date
=> Update file: start-grow-and-scale-online date

_digital-programmes/masterclasses-&-workshops/digital-strategy-the-101-of-search-engine-optimisation-seo.md, _digital-programmes/masterclasses-&-workshops/omni-commerce-retail.md
Update dates for SEO and Omni Channel Masterclass
=> Update dates for SEO and Omni Channel Masterclass

_wsq-programmes/WSQ-certified-modular-programmes/the-art-and-science-of-visual-merchandising.md
=> Edit error

_digital-programmes/alibaba-business-school/alibaba-content-marketing-programme.md, _digital-programmes/alibaba-business-school/alibaba-managerial-elite-programme.md, _digital-programmes/masterclasses-&-workshops/google-analytics-ga-for-e-commerce-with-gaiq-certification.md, _digital-programmes/masterclasses-&-workshops/master-linkedin-for-sales-marketing.md
ATU CM, Masterclasses - LinkedIn & GAIQ
=> Updated intake dates

_digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md, _services/career-services/sgus-digital-and-leadership-skills-to-excel-in-the-future-of-retail-and-business.md, _services/career-services/sgus-manage-retail-enterprise-in-the-digital-age.md, _services/career-services/sgus-omni-commerce-and-digital-marketing.md
=> update ESP 

_about-us/who-we-are.md, _services/collection.yml, _services/consultancy/SkillsFuture Enterprise Credit (SFEC).md, _services/consultancy/overview.md
- Updated the funding eligibility date in "About Us" page
- Created new funding page for SFEC 
- Updated new funding under "Consultancy Overview" page
=> About Us and New Funding Page

_digital-programmes/skillsfuture-for-digital-workplace-sfdw.md
=> Update Date of SFDW

_about-us/contact-us.md, _services/consultancy/absentee-payroll-ap.md, _services/consultancy/enhanced-training-support-for-smes-etss.md, _services/consultancy/skillsfuture-qualification-award.md, _services/consultancy/skillsfuture-study-awards.md, _wsq-programmes/WSQ-certified-modular-programmes/creating-an-unforgettable-customer-experience.md, _wsq-programmes/WSQ-certified-modular-programmes/mastering-the-art-of-selling-in-new-retail.md, _wsq-programmes/WSQ-certified-modular-programmes/maximise-digital-advertising-dollars-with-search-engine-marketing-sem.md, _wsq-programmes/WSQ-certified-modular-programmes/search-engine-optimization-seo-game-plan.md, _wsq-programmes/WSQ-certified-modular-programmes/the-art-and-science-of-visual-merchandising.md, _wsq-programmes/WSQ-certified-modular-programmes/unleash-the-power-of-social-media-marketing.md, _wsq-programmes/WSQ-full-qualification-programmes/advanced-certificate-in-retail-operations.md, _wsq-programmes/WSQ-full-qualification-programmes/certificate-in-retail-operations.md, _wsq-programmes/WSQ-full-qualification-programmes/diploma-in-retail-e-commerce-omni-channel.md, _wsq-programmes/WSQ-full-qualification-programmes/diploma-in-retail-operations.md, _wsq-programmes/WSQ-full-qualification-programmes/specialist-diploma-in-retail-operations.md
Updates of SSG Funding changes, Marketing Guidelines and Adding of SFEC (first batch)
=> Updates of SSG Funding changes, Marketing Guidelines and Adding of SFEC (first batch)

_digital-programmes/masterclasses-&-workshops/3-steps-to-digitise-your-business.md, _digital-programmes/masterclasses-&-workshops/Smart Social Commerce.md, _digital-programmes/masterclasses-&-workshops/category-management-the-key-to-business-growth.md, _digital-programmes/masterclasses-&-workshops/differentiate-and-drive-growth-with-experience-innovation.md, _digital-programmes/masterclasses-&-workshops/digital-commerce-operations.md, _digital-programmes/masterclasses-&-workshops/empower-your-business-with-social-commerce-digital-payment.md, _digital-programmes/masterclasses-&-workshops/improve-customer-engagement-with-digital-mindset.md
Updates of SSG marketing guidelines (last batch) -BD's masterclasses and workshops
=> Updates of SSG marketing guidelines (last batch)

_digital-programmes/skillsfuture-for-digital-workplace-sfdw.md
Change of Date for SFDW requested by trainer
=> Change of Date for SFDW 

_services/career-services/sgus-digital-and-leadership-skills-to-excel-in-the-future-of-retail-and-business.md, _services/career-services/sgus-omni-commerce-and-digital-marketing.md, _wsq-programmes/WSQ-certified-modular-programmes/creating-an-unforgettable-customer-experience.md
Amend Service Excellence and Update new dates for SGUS OC and DL
=> Amend Service Excellence and Update new dates for SGUS OC and DL

_digital-programmes/masterclasses-&-workshops/google-shopping-with-adwords-certified-professional-course.md, _wsq-programmes/WSQ-certified-modular-programmes/mastering-the-art-of-selling-in-new-retail.md, _wsq-programmes/WSQ-certified-modular-programmes/maximise-digital-advertising-dollars-with-search-engine-marketing-sem.md
=> Amend error in codes 

_wsq-programmes/WSQ-certified-modular-programmes/maximise-digital-advertising-dollars-with-search-engine-marketing-sem.md
Amend error in WSQ Paid Search Engine Marketing - SEM
=> Amend error in WSQ Paid Search Engine Marketing - SEM 

_services/consultancy/99-sme-campaign.md
Update contact - removed Lee Keng
=> Update file: 99-sme-campaign.md

_digital-programmes/alibaba-business-school/alibaba-content-marketing-programme.md, _digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md, _services/career-services/career-services-overview.md, _services/career-services/sgunited-skills-sgus-programme-overview.md, _services/career-services/sgus-digital-and-leadership-skills-to-excel-in-the-future-of-retail-and-business.md, _services/career-services/sgus-manage-retail-enterprise-in-the-digital-age.md, _services/career-services/sgus-omni-commerce-and-digital-marketing.md
=> Add call to action for SGUS

_digital-programmes/SkillsFuture-series/basics-in-content-generation.md, _digital-programmes/masterclasses-&-workshops/3-steps-to-digitise-your-business.md
=> Amendments

_digital-programmes/masterclasses-&-workshops/Smart Social Commerce.md
=> Amend Smart Social Commerce

_digital-programmes/alibaba-business-school/alibaba-content-marketing-programme.md, _digital-programmes/masterclasses-&-workshops/understanding-your-future-customers.md
Updated intake date & reg link
=> CM & WGSN Workshop

_wsq-programmes/WSQ-full-qualification-programmes/diploma-in-retail-operations.md, _wsq-programmes/WSQ-full-qualification-programmes/specialist-diploma-in-retail-operations.md
Change of intake takes and removal of SkillsFuture Award
=> Change of intake takes and removal of SkillsFuture Award

_digital-programmes/digital-mentorship-programme-dmp/boost-your-business-with-social-commerce.md, _digital-programmes/digital-mentorship-programme-dmp/jumpstart-your-online-business.md, _digital-programmes/e-commerce-programmes/best-practices-of-e-commerce-transactions-esg-tr-76.md, _digital-programmes/masterclasses-&-workshops/empower-your-business-with-social-commerce-digital-payment.md, _digital-programmes/masterclasses-&-workshops/improve-customer-engagement-with-digital-mindset.md
Updated intake dates & fees for DMP
=> TR 76, Empower your business MC, DMP

_services/consultancy/skillsfuture-study-awards.md, _wsq-programmes/WSQ-full-qualification-programmes/diploma-in-retail-e-commerce-omni-channel.md
Update WSQ Dip Omni-commerce on SkillsFuture Qualification Award and Study Award page
=> Update WSQ Dip Omni-commerce on SkillsFuture Qualification Award and Study Award page

_services/career-services/sgus-digital-and-leadership-skills-to-excel-in-the-future-of-retail-and-business.md, _services/career-services/sgus-manage-retail-enterprise-in-the-digital-age.md, _services/career-services/sgus-omni-commerce-and-digital-marketing.md
Update of intake dates for SGUS
=> Update of intake dates for SGUS

index.md
=> Updated Homepage Highlights

_digital-programmes/masterclasses-&-workshops/3-steps-to-digitise-your-business.md
=> Update file: 3-steps-to-digitise-your-business.md

_digital-programmes/alibaba-business-school/alibaba-content-marketing-programme.md, _digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md
=> Update ESP and CM with UTAP 

_services/career-services/sgus-digital-and-leadership-skills-to-excel-in-the-future-of-retail-and-business.md, _services/career-services/sgus-omni-commerce-and-digital-marketing.md
=> Update of intake dates

_digital-programmes/joint-certification-programmes/certified-digital-productivity-consultant.md
=> Update file: certified-digital-productivity-consultant.md

_services/career-services/career-services-overview.md, _services/career-services/sgunited-skills-sgus-programme-overview.md, _services/career-services/sgus-digital-and-leadership-skills-to-excel-in-the-future-of-retail-and-business.md, _services/career-services/sgus-manage-retail-enterprise-in-the-digital-age.md, _services/career-services/sgus-omni-commerce-and-digital-marketing.md, index.md
Update SGUS intake to be closed.
=> Update SGUS intake to be closed.

_digital-programmes/masterclasses-&-workshops/digital-commerce-operations.md
Removed error - additional sentence.
=> Update file: digital-commerce-operations.md

_digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md
=> Update Alibaba Text 

_digital-programmes/alibaba-business-school/alibaba-content-marketing-programme.md
=> Update file: alibaba-content-marketing-programme.md

_digital-programmes/SkillsFuture-series/personal-online-branding.md, _digital-programmes/e-commerce-programmes/amazon-global-selling-onboarding.md, _digital-programmes/e-commerce-programmes/drive-sales-performance-on-lazada-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-qoo10-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-shopee-marketing.md, _digital-programmes/e-commerce-programmes/ebay-global-selling-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-lazada-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-qoo10-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-shopee-onboarding.md, _digital-programmes/masterclasses-&-workshops/digital-commerce-visual.md, _digital-programmes/masterclasses-&-workshops/omni-commerce-retail.md
Update of intake dates (1st batch)
=> Update of intake dates (1st batch) 

_digital-programmes/masterclasses-&-workshops/Smart Social Commerce.md
=> Update file: Smart Social Commerce.md

_digital-programmes/SkillsFuture-series/basics-in-content-generation.md, _digital-programmes/SkillsFuture-series/engage-customers-through-social-media.md, _digital-programmes/SkillsFuture-series/fundamentals-to-starting-an-online-business.md, _digital-programmes/SkillsFuture-series/introduction-to-data-analytics.md, _digital-programmes/SkillsFuture-series/introduction-to-digital-marketing.md, _digital-programmes/SkillsFuture-series/personal-online-branding.md, _digital-programmes/SkillsFuture-series/tap-into-the-power-of-instagram-for-selling.md, _digital-programmes/SkillsFuture-series/thrive-in-digital-disruption.md, _digital-programmes/e-commerce-programmes/set-up-an-online-business.md, _digital-programmes/masterclasses-&-workshops/digital-strategy-the-101-of-search-engine-optimisation-seo.md, _wsq-programmes/WSQ-certified-modular-programmes/creating-an-unforgettable-customer-experience.md, _wsq-programmes/WSQ-certified-modular-programmes/mastering-the-art-of-selling-in-new-retail.md, _wsq-programmes/WSQ-certified-modular-programmes/maximise-digital-advertising-dollars-with-search-engine-marketing-sem.md, _wsq-programmes/WSQ-certified-modular-programmes/search-engine-optimization-seo-game-plan.md, _wsq-programmes/WSQ-certified-modular-programmes/the-art-and-science-of-visual-merchandising.md, _wsq-programmes/WSQ-certified-modular-programmes/unleash-the-power-of-social-media-marketing.md
Update intake dates (batch 2) and removal of UTAP funding for some courses as e2i has rejected some the courses for renewal.
=> Update intake dates (batch 2) and removal of UTAP funding for some courses 

_services/career-services/ccp-digital-professional-retail.md, _services/career-services/ccp-retail-professional.md
=> Change of CCP Links

_success-and-blog/blog/3-methods-to-enter-the-chinese-market.md, _success-and-blog/blog/overview.md
- Updated Overview i.e. removed year
- Added Amazon's blog URL in '3 methods to enter Chinese market'
=> Updated Blog

_digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md
=> Update ESP Dates

_digital-programmes/masterclasses-&-workshops/level-up-customer-engagement-through-live-streaming.md
On behalf of JW, updated: 
1. Revised intake date to 25 & 29 Apr instead of 22 & 25 Apr
2. May date remain
Above confirmed correct by Celeste Tan
=> Update intake dates

_digital-programmes/SkillsFuture-series/basics-in-content-generation.md, _digital-programmes/SkillsFuture-series/engage-customers-through-social-media.md, _digital-programmes/SkillsFuture-series/fundamentals-to-starting-an-online-business.md, _digital-programmes/SkillsFuture-series/personal-online-branding.md, _digital-programmes/SkillsFuture-series/tap-into-the-power-of-instagram-for-selling.md, _digital-programmes/SkillsFuture-series/thrive-in-digital-disruption.md, _digital-programmes/e-commerce-programmes/amazon-global-selling-onboarding.md, _digital-programmes/e-commerce-programmes/drive-sales-performance-on-lazada-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-qoo10-marketing.md, _digital-programmes/e-commerce-programmes/driving-sales-performance-on-shopee-marketing.md, _digital-programmes/e-commerce-programmes/getting-started-on-lazada-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-qoo10-onboarding.md, _digital-programmes/e-commerce-programmes/getting-started-on-shopee-onboarding.md, _digital-programmes/e-commerce-programmes/set-up-an-online-business.md, _digital-programmes/masterclasses-&-workshops/digital-commerce-visual.md, _digital-programmes/masterclasses-&-workshops/level-up-customer-engagement-through-live-streaming.md, _digital-programmes/masterclasses-&-workshops/omni-commerce-retail.md, _services/consultancy/overview.md, _wsq-programmes/WSQ-certified-modular-programmes/creating-an-unforgettable-customer-experience.md, _wsq-programmes/WSQ-certified-modular-programmes/mastering-the-art-of-selling-in-new-retail.md, _wsq-programmes/WSQ-certified-modular-programmes/unleash-the-power-of-social-media-marketing.md
=> Update of intake dates 

_digital-programmes/SkillsFuture-series/engage-customers-through-social-media.md, _digital-programmes/SkillsFuture-series/fundamentals-to-starting-an-online-business.md, _digital-programmes/SkillsFuture-series/tap-into-the-power-of-instagram-for-selling.md
=> Update of intake takes

_digital-programmes/masterclasses-&-workshops/level-up-customer-engagement-through-live-streaming.md
Update of mode for livestreaming
=> Update of mode for livestreaming

_success-and-articles/Articles/eTail Asia 2022.md
=> Code amendment

_digital-programmes/collection.yml, _digital-programmes/masterclasses-&-workshops/Demystify Emerging Digital Technologies in the New Retail Revolution.md, _digital-programmes/masterclasses-&-workshops/overview.md
Created new course webpage for new workshop - Demystify AI
=> New workshop - Demystify AI

_digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md
Update Alibaba ESP to be conducted in English for this intake
=> Update Alibaba ESP to be conducted in English for this intake

_digital-programmes/SkillsFuture-series/introduction-to-data-analytics.md, _digital-programmes/masterclasses-&-workshops/omni-commerce-retail.md
Change of dates (requested by Trainer)
=> Change of dates (requested by Trainer)

_digital-programmes/Visual Merchandising Mentorship Programme (VMMP).md
=> Update file: Visual Merchandising Mentorship Programme (VMMP).md

_digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md
Change ESP language to english class
=> Change ESP language to english class

_digital-programmes/e-commerce-programmes/ebay-global-selling-onboarding.md
Aidah informed cancellation of 9 Dec class
=> Update file: ebay-global-selling-onboarding.md

_digital-programmes/SkillsFuture-series/basics-in-content-generation.md
Cheryl informed on the change of intake date
=> Update file: basics-in-content-generation.md

index.md
=> Home Highlight

_digital-programmes/collection.yml, _digital-programmes/masterclasses-&-workshops/Building an Effective Digital Personal Brand.md, _digital-programmes/masterclasses-&-workshops/Smart Social Commerce.md, _digital-programmes/masterclasses-&-workshops/overview.md
Created a new course webpage for the workshop - Building an Effective Digital Personal Brand
=> New Workshop

_digital-programmes/masterclasses-&-workshops/Building an Effective Digital Personal Brand.md, _digital-programmes/masterclasses-&-workshops/Digital Transformation with a New Mindset.md, _digital-programmes/masterclasses-&-workshops/Mint Your FIrst Non Fungible Token (NFT) in Top Marketplaces.md, _digital-programmes/masterclasses-&-workshops/Power Up Your Content with Blockbuster Bullets.md
Updated course references and additional funding
=> Updates on SIRS Workshop Series

_digital-programmes/masterclasses-&-workshops/Holistic Wellness for a Resilient You.md, _digital-programmes/masterclasses-&-workshops/Power Up Your Content with Blockbuster Bullets.md
Update course references for SIRS Workshops
=> Update course references

_digital-programmes/SkillsFuture-series/introduction-to-digital-marketing.md, _digital-programmes/SkillsFuture-series/tap-into-the-power-of-instagram-for-selling.md, _digital-programmes/alibaba-business-school/alibaba-entrepreneur-startup-programme.md, _digital-programmes/e-commerce-programmes/set-up-an-online-business.md, _digital-programmes/masterclasses-&-workshops/Jumpstart and Grow Your Home Based Business.md, _digital-programmes/masterclasses-&-workshops/Mint Your First Non Fungible Token (NFT) in Top Marketplaces.md, _digital-programmes/masterclasses-&-workshops/Sell and Earn on TikTok.md, _digital-programmes/masterclasses-&-workshops/improve-customer-engagement-with-digital-mindset.md, _digital-programmes/masterclasses-&-workshops/level-up-customer-engagement-through-live-streaming.md, _wsq-programmes/WSQ-certified-modular-programmes/maximise-digital-advertising-dollars-with-search-engine-marketing-sem.md, _wsq-programmes/WSQ-certified-modular-programmes/search-engine-optimization-seo-game-plan.md
=> Update intake dates 

_digital-programmes/masterclasses-&-workshops/Holistic Wellness for a Resilient You.md
Change in intake date as per Aidah.
=> Update file: Holistic Wellness for a Resilient You.md

_digital-programmes/e-commerce-programmes/set-up-an-online-business.md
Amendment to intake date per Cheryl
=> Update file: set-up-an-online-business.md

_services/career-services/career-services-overview.md
=> Update file: career-services-overview.md

_digital-programmes/collection.yml, _digital-programmes/masterclasses-&-workshops/Building an Effective Digital Personal Brand.md, _digital-programmes/masterclasses-&-workshops/Digital Transformation with a New Mindset.md, _digital-programmes/masterclasses-&-workshops/Holistic Wellness for a Resilient You.md, _digital-programmes/masterclasses-&-workshops/Jumpstart and Grow Your Home Based Business.md, _digital-programmes/masterclasses-&-workshops/Mint Your First Non Fungible Token (NFT) in Top Marketplaces.md, _digital-programmes/masterclasses-&-workshops/Power Up Your Content with Blockbuster Bullets.md, _digital-programmes/masterclasses-&-workshops/Sell and Earn on TikTok.md, _digital-programmes/masterclasses-&-workshops/Smart Social Commerce.md, _digital-programmes/masterclasses-&-workshops/Start Your Business at No Cost Using Affiliate Marketing.md, _digital-programmes/masterclasses-&-workshops/digital-commerce-visual.md, _digital-programmes/masterclasses-&-workshops/improve-customer-engagement-with-digital-mindset.md, _digital-programmes/masterclasses-&-workshops/omni-commerce-retail.md, _digital-programmes/masterclasses-&-workshops/overview.md
Created page for new workshop and removed passed dates for Masterclasses/Workshops
=> New Workshop and Updates

_about-us/Our Team.md, _services/consultancy/enhanced-training-support-for-smes-etss.md, _services/consultancy/overview.md
- Update HOD - removed HODs group photo and removed Celeste YL profile
- Update BD contact - Removed Celeste YL, added CJ and Ceceilia
=> Update HOD and BD Contact

_about-us/contact-us.md, _digital-programmes/e-commerce-programmes/getting-started-on-shopee-onboarding.md
1 Dec class changed to Online instead of F2F per Aidah.
=> Update intake date

_digital-programmes/collection.yml, _digital-programmes/e-commerce-programmes/getting-started-on-shopee-onboarding.md, _digital-programmes/e-commerce-programmes/overview.md, _digital-programmes/masterclasses-&-workshops/CaseTrust Accreditation Scheme for E Commerce Business.md, _digital-programmes/masterclasses-&-workshops/overview.md, _success-and-articles/Articles/Retail Industry Transformation Map 2025.md
=> Update file: Retail Industry Transformation Map 2025.md

_digital-programmes/masterclasses-&-workshops/Digital Entrepreneurship in the Era of Cross Border E Commerce Mastering Selling Strategies on.md
Change registration form URL per Shermaine
=> Change registration form URL per Shermaine

_digital-programmes/alibaba-business-school/alibaba-ceo-master-programme.md
Updated MCEO intake date to 10 - 16 Sep
=> Update MCEO intake date

_digital-programmes/alibaba-business-school/alibaba-ceo-master-programme.md
=> Updated ATU MCEO Reg Link
